# Generated by Django 5.0.14 on 2025-08-05 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_seguro', models.CharField(max_length=70)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('lugar_procedencia', models.CharField(max_length=100)),
                ('n_hcl', models.CharField(max_length=20, verbose_name='Número de Historia Clínica')),
                ('fecha_hora_cita_otorgada', models.DateTimeField()),
                ('fecha_hora_atencion', models.DateTimeField()),
                ('diagnostico_medico', models.TextField()),
                ('dx_CIE_10_1', models.CharField(max_length=10, verbose_name='Diagnóstico CIE-10 Principal')),
                ('dx_CIE_10_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Diagnóstico CIE-10 Secundario')),
                ('dx_CIE_10_3', models.CharField(blank=True, max_length=10, null=True, verbose_name='Diagnóstico CIE-10 Terciario')),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
