# Generated by Django 5.0.14 on 2025-08-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Tablero')),
                ('url', models.URLField(max_length=500, verbose_name='URL del Tablero')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('source', models.CharField(max_length=255, verbose_name='Fuente de datos')),
                ('last_updated', models.DateTimeField(verbose_name='Última actualización')),
                ('update_frequency', models.TextField(blank=True, null=True, verbose_name='Frecuencia de actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tablero',
                'verbose_name_plural': 'Tableros',
                'ordering': ['name'],
            },
        ),
    ]
