# Generated by Django 5.0.14 on 2025-08-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimon', '0002_tablero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
