# Generated by Django 5.0.14 on 2025-08-30 04:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimon', '0003_tablero_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='codigo_embed',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
