# Generated by Django 5.0.14 on 2025-09-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimon', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Tablero')),
                ('frecuencia', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dimon.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['nombre'],
            },
        ),
    ]
