# Generated by Django 5.0.14 on 2025-09-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimon', '0006_fuentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablero',
            name='fuentes',
            field=models.ManyToManyField(blank=True, related_name='tableros', to='dimon.fuentes', verbose_name='Fuentes de datos'),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Anual', 'Anual')], max_length=20, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='fuentes',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la fuente'),
        ),
    ]
