# Generated by Django 5.0.14 on 2025-08-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_user_deleted_at_remove_user_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nivel_acceso',
        ),
    ]
