# Generated by Django 5.0.14 on 2025-08-17 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('TOYOTA', 'Toyota'), ('NISSAN', 'Nissan'), ('HYUNDAI', 'Hyundai')], max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('asientos', models.PositiveIntegerField(default=5)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En mantenimiento'), ('EN_USO', 'En uso')], default='DISPONIBLE', max_length=20)),
                ('kilometraje', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='es_conductor',
        ),
        migrations.AlterField(
            model_name='personal',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personales', to='administracion.dependencia'),
        ),
    ]
