# Generated by Django 5.0.14 on 2025-08-17 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_vehiculo_remove_personal_es_conductor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('ipress_nombre', models.CharField(max_length=100)),
                ('ipress_categoria', models.CharField(max_length=50)),
                ('ipress_ubicacion', models.CharField(max_length=150)),
                ('ipress_codigo', models.CharField(blank=True, max_length=20)),
                ('conductor', models.CharField(max_length=100)),
                ('personal_1', models.CharField(blank=True, max_length=100)),
                ('personal_2', models.CharField(blank=True, max_length=100)),
                ('personal_3', models.CharField(blank=True, max_length=100)),
                ('personal_4', models.CharField(blank=True, max_length=100)),
                ('reprogramacion', models.BooleanField(default=False)),
                ('motivo_reprogramacion', models.CharField(blank=True, max_length=50, null=True)),
                ('hoja_salida', models.FileField(blank=True, null=True, upload_to='comisiones/hojas/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.vehiculo')),
            ],
        ),
    ]
