# Generated by Django 5.0.14 on 2025-08-17 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['-fecha_salida'], 'verbose_name': 'Comisión'},
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='ipress_ubicacion',
            new_name='ipress_departamento',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='personal_1',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='personal_2',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='personal_3',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='personal_4',
        ),
        migrations.AddField(
            model_name='comision',
            name='ipress_disa',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='ipress_distrito',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='ipress_este',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='ipress_institucion',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='ipress_norte',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='ipress_provincia',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comision',
            name='participantes',
            field=models.ManyToManyField(blank=True, help_text='Máximo 4 participantes (5 incluyendo conductor)', limit_choices_to={'activo': True}, related_name='comisiones_participante', to='administracion.personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='es_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comision',
            name='conductor',
            field=models.ForeignKey(limit_choices_to={'activo': True, 'es_conductor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_conductor', to='administracion.personal'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_categoria',
            field=models.CharField(max_length=150),
        ),
    ]
