# Generated by Django 5.0.14 on 2025-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_comision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
