# Generated by Django 5.0.14 on 2025-08-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_personal_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profesion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
