# Generated by Django 5.0.14 on 2025-08-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_personal_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En mantenimiento'), ('EN_USO', 'En uso')], default='DISPONIBLE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
