# Generated by Django 5.0.14 on 2025-08-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_alter_vehiculo_estado_alter_vehiculo_kilometraje_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comision',
            old_name='fecha_ingreso',
            new_name='fecha_retorno',
        ),
    ]
