# Generated by Django 5.0.14 on 2025-08-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_rename_fecha_ingreso_comision_fecha_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='ipress_categoria',
            field=models.CharField(max_length=50),
        ),
    ]
