# Generated by Django 5.0.14 on 2025-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_alter_comision_ipress_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='ipress_categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_departamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_disa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_distrito',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_este',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_institucion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_norte',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='ipress_provincia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
