# Generated by Django 5.0.14 on 2025-08-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_comision_ipress_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comision',
            old_name='creado_por',
            new_name='created_by',
        ),
    ]
