# Generated by Django 5.0.14 on 2025-08-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_rename_creado_por_comision_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='acceso',
            field=models.BooleanField(default=False, verbose_name='Tiene acceso al sistema'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_habilitacion_acceso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de habilitación de acceso'),
        ),
        migrations.AddField(
            model_name='personal',
            name='habilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_habilitado', to=settings.AUTH_USER_MODEL, verbose_name='Habilitado por'),
        ),
    ]
