# Generated by Django 5.0.14 on 2025-08-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_personal_acceso_personal_fecha_habilitacion_acceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
