# Generated by Django 5.0.14 on 2025-08-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_personal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Celular'),
        ),
    ]
