# Generated by Django 5.0.14 on 2025-08-31 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_personal_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email_per',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='ruc',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
