# Generated by Django 5.0.14 on 2025-08-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_personal_email_per_personal_ruc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='profesion',
            new_name='n_contrato',
        ),
        migrations.AddField(
            model_name='personal',
            name='cel_emergencia',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Celuklar de emergencia'),
        ),
        migrations.AddField(
            model_name='personal',
            name='cont_emergencia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha fin'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='personal',
            name='n_hijos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='padre_madre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario'),
        ),
        migrations.AddField(
            model_name='personal',
            name='sexo',
            field=models.CharField(default=1, max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='acceso',
            field=models.BooleanField(default=False, verbose_name='acceso al sistema'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo institucional'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC'),
        ),
    ]
