# Generated by Django 5.0.14 on 2025-08-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_anexo_condition_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Generica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('detalle', models.CharField(max_length=255, verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Generica',
                'verbose_name_plural': 'Genericas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoOcupacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Grupo Ocupacional')),
            ],
            options={
                'verbose_name': 'GrupoOcupacional',
                'verbose_name_plural': 'GrupoOcupacionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['nombre'], 'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
        migrations.AddField(
            model_name='area',
            name='nombre',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
