# Generated by Django 5.0.14 on 2025-08-31 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_cargo_estado_generica_grupoocupacional_profesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='anexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.anexo', verbose_name='Anexo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personales', to='administracion.area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='personal',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.condition', verbose_name='condición'),
        ),
        migrations.AddField(
            model_name='personal',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.estado', verbose_name='Estado laboral'),
        ),
        migrations.AddField(
            model_name='personal',
            name='generica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.generica', verbose_name='Genérica'),
        ),
        migrations.AddField(
            model_name='personal',
            name='grupo_ocupacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.grupoocupacional', verbose_name='Grupo Ocupacional'),
        ),
        migrations.AddField(
            model_name='personal',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.profesion', verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personales', to='administracion.dependencia', verbose_name='Dependencia'),
        ),
    ]
