# Generated by Django 5.0.14 on 2025-08-31 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0020_personal_anexo_personal_area_personal_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Nivels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.nivel', verbose_name='Nivel'),
        ),
    ]
