# Generated by Django 5.0.14 on 2025-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0021_nivel_personal_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Regimen',
                'verbose_name_plural': 'Regimen',
                'ordering': ['nombre'],
            },
        ),
    ]
