# Generated by Django 5.0.14 on 2025-08-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0022_regimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.regimen', verbose_name='Regimen'),
        ),
    ]
