# Generated by Django 5.0.14 on 2025-08-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_personal_regimen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cel_emergencia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celuklar de emergencia'),
        ),
    ]
