# Generated by Django 5.0.14 on 2025-08-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_alter_personal_cel_emergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='posicion',
        ),
    ]
