# Generated by Django 5.0.14 on 2025-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0025_remove_personal_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cel_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celuklar de emergencia'),
        ),
    ]
