# Generated by Django 5.0.14 on 2025-08-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_alter_personal_cel_emergencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personals'},
        ),
    ]
