# Generated by Django 5.0.14 on 2025-08-31 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_alter_personal_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personal',
            table='administracion_personal',
        ),
    ]
