# Generated by Django 5.0.14 on 2025-08-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0028_alter_personal_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelTable(
            name='personal',
            table=None,
        ),
    ]
