# Generated by Django 5.0.14 on 2025-09-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_personal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='sexo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
