# Generated by Django 5.0.14 on 2025-09-04 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0031_alter_personal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
