# Generated by Django 5.0.14 on 2025-09-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0032_alter_personal_celular_alter_personal_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='personal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to='administracion.personal', verbose_name='Actualizado por'),
        ),
    ]
