# Generated by Django 5.0.14 on 2025-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_personal_updated_at_personal_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
