# Generated by Django 5.0.14 on 2025-08-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_online',
        ),
    ]
