# Generated by Django 5.0.14 on 2025-08-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_historicaluser_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='red',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='red',
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Departamento'),
        ),
    ]
