# Generated by Django 5.0.14 on 2025-08-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_historicaluser_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de login')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('device_type', models.CharField(choices=[('PC', 'Computadora'), ('MOBILE', 'Móvil'), ('TABLET', 'Tablet'), ('OTHER', 'Otro')], max_length=10, verbose_name='Tipo de dispositivo')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('logout_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de logout')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clave de sesión')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario',
                'verbose_name_plural': 'Auditorías de Usuarios',
                'ordering': ['-login_date'],
            },
        ),
    ]
