# Generated by Django 5.0.14 on 2025-08-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_useraudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='login_blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta'),
        ),
    ]
