# Generated by Django 5.0.14 on 2025-08-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_historicaluser_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='user',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='distrito',
        ),
    ]
