# Generated by Django 5.0.14 on 2025-08-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_historicaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_by',
        ),
    ]
