# Generated by Django 5.0.14 on 2025-08-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_historicaluser_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='nivel_acceso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nivel_acceso',
        ),
    ]
